For MSVC use alloca() instead of VLA
sphincs/sphincsplus pull request #26
Opened 2021-12-29 12:18 UTC by bwesterb

Closes #20

@thomwiggers

2021-12-30 09:31 UTC, thomwiggers commented
Was this tested? AFAICT MSVC doesn't have alloca, but it does have _alloca (deprecated) in malloc.h (for maximum confusion).

2021-12-30 15:38 UTC, sfluhrer commented
I'm not certain that allocating variable length automatic arrays (either with VLAs or using alloca) is the Right Thing.  Two examples:
- haraka_S_absorb - the rate is always 32 - why do we need a variable length array?
- thash (the robust versions) - currently, we allocate the full array, generate the full mask, and xor it in.  An alternative approach would be generate the mask one block at a time, and process it incrementally - see https://github.com/sphincs/parallel-sphincsplus/blob/main/shake256_robust.cpp for an example of that being done.

2022-07-19 10:09 UTC, thomwiggers requested changes

2022-07-19 10:09 UTC, thomwiggers commented on ref/utils.h
> +# define SPX_VLA(__t,__x,__s) __t *__x = (__t*)alloca((__s)*sizeof(__t))
```suggestion
/* MSVC defines _alloca in malloc.h */
# include <malloc.h>
/* Note: _malloca(), which is recommended over deprecated _alloca,
   requires that you call _freea(). So we stick with _alloca */ 
# define SPX_VLA(__t,__x,__s) __t *__x = (__t*)_alloca((__s)*sizeof(__t))
```

This is required for Windows support as tested on Godbolt.

2022-08-02 14:58 UTC, thomwiggers commented
Even though this perhaps isn't at all the best way to solve this, it would be great if we can actually merge some form of this PR so that we can proceed with updating PQClean (and OQS downstream).

2022-08-02 15:51 UTC, bwesterb commented
@sfluhrer I want to propose to merge a rebased version of this patch together with Thom's suggestion for now. Then, later, we can get rid of the variable sized arrays alltogether.

2022-08-02 15:55 UTC, sfluhrer approved these changes

2022-08-02 21:16 UTC, bwesterb commented
@thomwiggers Rebased. If builds pass, please give it a double-check.

2022-08-03 10:35 UTC, thomwiggers commented
Seems to compile just fine. There's some more work needed before this repo will produce useful binaries (mostly because the test binaries here use OpenSSL and the random number generator isn't set up for Windows) -- but I'm not getting VLA problems here.

2022-08-03 11:12 UTC, merged